### ISSUE TITLE
New error on classification: ValueError: optimizer got an empty parameter list

### ISSUE THREAD

**Issue by wozcoder** [loiccordone/object-detection-with-spiking-neural-networks#13]
Hello Loic,
After updating the code and attepmting to replicate classification results. I am seeing this new error. 
Could you please help me out with this? 
What could be the cause of this?
Attached is the error output.
Regards,
Below is my command input:
![runcommand](https://user-images.githubusercontent.com/108584911/183776077-f7e84bca-7e21-4fca-a39c-64479ab653db.png)

Below is the error output:
![new_error](https://user-images.githubusercontent.com/108584911/183775522-80c660b6-a4af-40d5-8a45-b7843d745ebd.png)

**Comment by loiccordone** [comment]
Hello wozcoder,
Thank you for your interest in our work but I don't have time to provide you support every day. 
You're seeing this error because you don't use the right formatting for the model name, it should be "densenet-121_16".
This information could have been obtained in the code:
https://github.com/loiccordone/object-detection-with-spiking-neural-networks/blob/d52e6e803ee776095d313af862f01cac068da899/models/utils.py#L38-L46
